---
- name: ensure ~/Bin directory is ready
  file: path=~/Bin
        state=directory
        recurse=yes

- name: ensure ve is installed
  get_url: url=https://raw.github.com/baijian/ve/master/ve
           dest=~/Bin/ve
           mode=0755
           force={{ force_download_bin_files }}
           validate_certs={{ force_download_validate }}

- name: copy Bin files
  copy: src={{ item }}
        dest=~/Bin/{{ item }}
        mode=0755
  with_items:
    - tunnel

