---
- name: ensure tmux is installed - MacOS
  homebrew: name=tmux state=present
  when: ansible_distribution == 'MacOSX'

- name: ensure tmux is installed - Ubuntu
  sudo: yes
  apt: pkg=tmux state=present
  when: ansible_distribution == 'Ubuntu'

- name: configure tmux
  template: src=tmux.conf dest=~/.tmux.conf
